'''
Expose json extraction tools to the models.
'''

from typing import Iterable, List
from langchain_core.tools import tool
from agentic_dd.extraction.jsonExtraction import *
from agentic_dd.extraction.jsonExtraction import is_docling_json as _is_docling_json_impl
from agentic_dd.agentlib.tools import register_tool


# -------- Define tools -------- #
@tool
def json_schema_outline(path: str, max_depth: int | None = None) -> list[dict]:
    ''' Get a generator holding the outline of a .json file. If more than one operation
    on this schema is supposed to happen, convert it to a list '''
    data = load_json(path)
    entries = list(schema(data))
    if max_depth is not None:
        entries = [e for e in entries if e.lvl <= max_depth]
    return [{"path": path_to_string(e.path), "lvl": e.lvl, "type": e.type} for e in entries]

@tool
def schema_to_list(schema_entries: Iterable[SchemaEntry]):
    ''' return a list from a schema generator iterable, use only after first calling json_schema_outline.
    Use only if the schema is to be queried multiple times '''
    return list(schema_entries)


@tool
def get_json_entity_by_path(path: str, key_path: str) -> str:
    """Retrieve a value from a JSON file at a dot-separated path (e.g. 'items.0.name')."""
    data = load_json(path)
    parts = tuple(int(p) if p.isdigit() else p for p in key_path.split("."))
    return str(get_by_path(data, parts))

@tool
def is_docling_json(json_dict: dict) -> bool:
    ''' Returns True if the json file was generated by docling, false else '''
    return _is_docling_json_impl(json_dict)   # was: self-recursive call to is_docling_json


@tool
def get_path_children(schema_entries: Iterable[SchemaEntry], parent_path: tuple[str | int, ...]) -> List[SchemaEntry]:
    ''' For an entity of a generaed json schema, get its children, pass its path with entity.path '''
    return children(schema_entries, parent_path)

@tool
def get_path_descendants(schema_entries: Iterable[SchemaEntry], parent: tuple[str | int, ...]) -> List[SchemaEntry]:
    ''' Get all descendants from a path '''
    return descendants(schema_entries, parent)   # was: parent_path (undefined)

@tool
def get_entities_of_type(schema_entries: Iterable[SchemaEntry], typ: str) -> List[SchemaEntry]:
    ''' get all entities of a specified type. Pass type attribute like entity.type '''
    return of_type(schema_entries, typ)

@tool
def get_keys_for_level(schema_entries: Iterable[SchemaEntry], lvl: int) -> List[tuple[str | int, ...]]:
    ''' for a given level of the json hierarchy, return the paths of entities on that level '''
    return level_keys(schema_entries, lvl)

# -------- Register tools -------- #
register_tool('json_schema_outline', json_schema_outline)
register_tool('schema_to_list', schema_to_list)
register_tool('get_json_entity_by_path', get_json_entity_by_path)
register_tool('is_docling_json', is_docling_json)
register_tool('get_path_children', get_path_children)
register_tool('get_path_descendants', get_path_descendants)
register_tool('get_entities_of_type', get_entities_of_type)
register_tool('get_keys_for_level', get_keys_for_level)